# Generated by Django 5.2 on 2025-09-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mada_journey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='destination',
            field=models.TextField(blank=True, help_text='Destination principale du circuit'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
