# Generated by Django 5.2 on 2025-07-23 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mada_journey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('vehicule', 'Véhicule'), ('circuit', 'Circuit')], default='vehicule', max_length=20, verbose_name='Reservation Type'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='circuit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='mada_journey.circuit'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='mada_journey.vehicule'),
        ),
    ]
