# Generated by Django 5.2 on 2025-07-31 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mada_journey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='vehicule_recommande',
            field=models.ForeignKey(blank=True, help_text='Véhicule recommandé pour ce circuit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuits', to='mada_journey.vehicule'),
        ),
    ]
