# Generated by Django 5.2 on 2025-07-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mada_journey', '0002_blogimage_circuitimage_destinationimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='image',
        ),
    ]
