# Generated by Django 5.2 on 2025-09-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mada_journey', '0002_alter_circuit_description_alter_circuit_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_type',
            field=models.CharField(choices=[('media', 'Média (Photos/Vidéos)'), ('youtube', 'Vidéo YouTube'), ('mixed', 'Contenu mixte')], default='media', help_text='Type de contenu du blog', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='youtube_embed_id',
            field=models.CharField(blank=True, help_text="ID d'intégration YouTube (généré automatiquement)", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='URL de la vidéo YouTube (optionnel)', null=True),
        ),
    ]
