# Generated by Django 5.2 on 2025-09-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mada_journey', '0003_blog_content_type_blog_youtube_embed_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='annee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='capacite',
            field=models.IntegerField(blank=True, help_text='Nombre de places assises', null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='marque',
            field=models.CharField(blank=True, help_text='Marque du véhicule (ex: Toyota, Ford)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='modele',
            field=models.CharField(blank=True, help_text='Modèle du véhicule (ex: Corolla, Focus)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type',
            field=models.CharField(blank=True, help_text='Type de véhicule (ex: 4x4, berline)', max_length=100, null=True),
        ),
    ]
