services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: madaga47_solidaire_db
      MYSQL_USER: madaga47_solidaire_db
      MYSQL_PASSWORD: WJVKHdayMuhT5Vyg3Vtr
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    environment:
      VITE_API_URL: http://localhost/graphql/
      HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: true
      NODE_ENV: development
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app:cached
    environment:
      DEBUG: 1
      DJANGO_ALLOWED_HOSTS: 0.0.0.0
      DB_NAME: madaga47_solidaire_db
      DB_USER: madaga47_solidaire_db
      DB_PASSWORD: WJVKHdayMuhT5Vyg3Vtr
      DB_HOST: mysql
      DB_PORT: 3306
    restart: always
    networks:
      - app-network
    depends_on:
    - mysql

volumes:
  backend:
  frontend_node_modules:
  mysql_data:

networks:
  app-network:
    driver: bridge
