"""
Django settings for explore_mada_journey project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from dotenv import load_dotenv
import os
from pathlib import Path
from datetime import timedelta

# Cette section force la désactivation de toute vérification CSRF
import django.conf.global_settings as DEFAULT_SETTINGS

CSRF_TRUSTED_ORIGINS = ["https://api.madagascar-voyagesolidaire.com"]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Créer le répertoire des logs s'il n'existe pas
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "[%(asctime)s] %(levelname)s %(name)s: %(message)s"
        },
        "verbose": {
            "format": "[%(asctime)s] %(levelname)s %(name)s "
                      "(%(filename)s:%(lineno)d): %(message)s"
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "formatter": "verbose",
            "filename": os.path.join(BASE_DIR, "logs", "app.log"),
            "maxBytes": 5 * 1024 * 1024,  # 5 MB
            "backupCount": 5,
            "encoding": "utf-8",
        },
        # Optionnel : pour capturer les erreurs critiques séparément
        "errors_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "formatter": "verbose",
            "filename": os.path.join(BASE_DIR, "logs", "errors.log"),
            "level": "ERROR",
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 3,
            "encoding": "utf-8",
        },
    },
    "loggers": {
        # Logger racine
        "": {
            "handlers": ["console", "file"],
            "level": "INFO",
        },
        # Logger pour Django (évite de surcharger avec DEBUG de django.db)
        "django": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        # Exemple : logger pour les erreurs critiques en plus
        "myapp": {
            "handlers": ["console", "file", "errors_file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Import default_headers after defining BASE_DIR
from corsheaders.defaults import default_headers

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=-^c))dt)dbi(g%h2kmtgkp)o!q3cr12=m0cs2#3(j2jg(qodf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# ALLOWED_HOSTS = [
#     'madagascar-voyagesolidaire.com', 
#     'api.madagascar-voyagesolidaire.com', 
#     'administration.madagascar-voyagesolidaire.com'
#     ]

# Fonction utilitaire pour les listes d'environnement
def get_list_env(var, default=None):
    val = os.getenv(var)
    if val:
        # Supporte format JSON ou liste séparée par virgule
        try:
            import ast
            return ast.literal_eval(val)
        except Exception:
            return [v.strip() for v in val.split(',') if v.strip()]
    return default or []

# Configuration pour proxy reverse et HTTPS
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Détection HTTPS dynamique
def is_production_https():
    """Détecte si on est en environnement HTTPS de production"""
    return any([
        os.environ.get('HTTPS') == 'on',
        os.environ.get('HTTP_X_FORWARDED_PROTO') == 'https',
        os.environ.get('DJANGO_ENV') == 'production',
        'administration.madagascar-voyagesolidaire.com' in os.environ.get('HTTP_HOST', '')
    ])

# Configuration des cookies conditionnelle pour HTTPS/HTTP
IS_PRODUCTION_HTTPS = is_production_https()

# Configuration des cookies de session
SESSION_COOKIE_SECURE = IS_PRODUCTION_HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_DOMAIN = '.madagascar-voyagesolidaire.com'
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_AGE = 86400  # 24 heures
SESSION_COOKIE_NAME = 'sessionid'
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

CORS_ALLOWED_ORIGINS = [
    'https://madagascar-voyagesolidaire.com',
    'https://api.madagascar-voyagesolidaire.com',
    'https://administration.madagascar-voyagesolidaire.com',
    'http://5.101.142.84:8000',
]

CSRF_TRUSTED_ORIGINS = [
    'https://madagascar-voyagesolidaire.com',
    'https://api.madagascar-voyagesolidaire.com',
    'https://administration.madagascar-voyagesolidaire.com',
    'http://5.101.142.84:8000'
]

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    "apollo-require-preflight",
    'apollographql-client-name',
    'apollographql-client-version',
    # Add these variations
    'ApolloGraphQL-Client-Name',
    'ApolloGraphQL-Client-Version',
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

# Application definition
INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "graphene_file_upload",
    'graphene_django',
    'graphql_jwt',
    "graphql_jwt.refresh_token",
    'rest_framework',
    'django_filters',
    'mada_journey',
]

GRAPHENE = {
    'SCHEMA': 'schema_root.schema',
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ],
}

# Middleware SANS CsrfViewMiddleware - TOTALEMENT RETIRÉ + Middleware custom
MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'mada_journey.middleware.DisableCSRFMiddleware',  # Middleware personnalisé pour désactiver CSRF
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # RETIRÉ COMPLÈTEMENT
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# DÉSACTIVATION COMPLÈTE DE CSRF
CSRF_COOKIE_SECURE = True
CSRF_USE_SESSIONS = True

# En production, définir les en-têtes de sécurité appropriés
# Avec cette configuration, votre application redirigera toutes les requêtes HTTP vers HTTPS et activera les en-têtes HSTS pour appliquer des connexions sécurisées.
# SECURE_HSTS_SECONDS = 3600   # Définir la durée HSTS 
# SECURE_SSL_REDIRECT = True   # Rediriger toutes les requêtes HTTP vers HTTPS

ROOT_URLCONF = 'explore_mada_journey.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'explore_mada_journey.wsgi.application'

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'madaga47_solidaire_db',
        'USER': 'madaga47_solidaire_db',    
        'PASSWORD': 'WJVKHdayMuhT5Vyg3Vtr',
        'HOST': '5.101.142.84',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            # Supprimez toutes les options liées aux plugins
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

AUTH_USER_MODEL = 'mada_journey.Utilisateur'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# CORRECTION PRINCIPALE : Configuration WhiteNoise simplifiée et correcte
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Configuration complète des fichiers statiques
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Répertoires de fichiers statiques pour le développement
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
] if DEBUG else []

# Configuration WhiteNoise optimisée
WHITENOISE_USE_FINDERS = DEBUG
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_INDEX_FILE = True

# IMPORTANT : Configuration pour servir les fichiers admin Django
WHITENOISE_STATIC_PREFIX = '/static/'

# Types MIME pour WhiteNoise
WHITENOISE_MIMETYPES = {
    '.css': 'text/css',
    '.js': 'application/javascript',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.gif': 'image/gif',
    '.svg': 'image/svg+xml',
    '.ico': 'image/x-icon',
    '.woff': 'font/woff',
    '.woff2': 'font/woff2',
    '.ttf': 'font/ttf',
    '.eot': 'application/vnd.ms-fontobject',
}

# Servir les fichiers admin même avec WhiteNoise
WHITENOISE_SKIP_COMPRESS_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'gz', 'tgz', 'bz2', 'tbz', 'xz', 'br']

WHITENOISE_COMPRESSION = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Configuration de stockage d'image:
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuration pour le développement - servir les fichiers médias
if DEBUG:
    from django.conf.urls.static import static

# Configuration des tailles d'upload
FILE_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024  # 15MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024   # 15MB

# Configuration de sécurité pour les fichiers
ALLOWED_IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif', '.webp']
MAX_IMAGE_SIZE = 15 * 1024 * 1024  # 15MB

# Configuration du cache pour optimiser l'admin
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

#  Configuration pour le JWT dans GraphQL
GRAPHQL_JWT = {
    'JWT_VERIFY_EXPIRATION': True,
    "JWT_LONG_RUNNING_REFRESH_TOKEN": True,
    'JWT_EXPIRATION_DELTA': timedelta(days=7),
    'JWT_AUTH_HEADER_PREFIX': 'JWT', 
    "JWT_REFRESH_EXPIRATION_DELTA": timedelta(days=7),
    'JWT_ALGORITHM': 'HS256',
}

AUTHENTICATION_BACKENDS = [
    'graphql_jwt.backends.JSONWebTokenBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # Utilisez AllowAny pour un accès public temporaire pendant le développement
        'rest_framework.permissions.AllowAny',
        # En production, utilisez plutôt:
        # 'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Configuration de sécurité pour la production
if IS_PRODUCTION_HTTPS:
    # Headers de sécurité HTTPS
    SECURE_SSL_REDIRECT = True  # Géré par le proxy
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

# Configuration pour servir les fichiers admin en développement
if DEBUG:
    # Assurer que les fichiers statiques de l'admin sont servis
    import django
    from django.conf.urls.static import static
    
# Configuration additionnelle pour le proxy PHP
# Ces paramètres aident le proxy à mieux gérer les requêtes
APPEND_SLASH = True
PREPEND_WWW = False

# Configuration spéciale pour les requêtes via proxy
ALLOWED_HOSTS_UNSAFE = False  # Gardez False pour la sécurité

# Variables d'environnement pour debug (optionnel)
if DEBUG:
    print(f"IS_PRODUCTION_HTTPS: {IS_PRODUCTION_HTTPS}")
    print(f"SESSION_COOKIE_SECURE: {SESSION_COOKIE_SECURE}")
    print("CSRF Protection: DISABLED")

# DÉSACTIVATION TOTALE ET EXPLICITE DE CSRF
# Cette section force la désactivation de toute vérification CSRF
USE_CSRF = False

# Monkey patch pour désactiver complètement CSRF au niveau système
try:
    import django.middleware.csrf
    # Remplacer le middleware CSRF par un middleware vide
    original_csrf_middleware = django.middleware.csrf.CsrfViewMiddleware
    
    class DummyCSRFMiddleware:
        def __init__(self, get_response):
            self.get_response = get_response
        
        def __call__(self, request):
            setattr(request, '_dont_enforce_csrf_checks', True)
            return self.get_response(request)
        
        def process_view(self, request, view_func, view_args, view_kwargs):
            setattr(request, '_dont_enforce_csrf_checks', True)
            return None
    
    django.middleware.csrf.CsrfViewMiddleware = DummyCSRFMiddleware
    
    print("CSRF Middleware successfully disabled via monkey patch")
except Exception as e:
    print(f"Warning: Could not monkey patch CSRF middleware: {e}")

# Supprimer les vérifications CSRF du système de checks
SILENCED_SYSTEM_CHECKS = [
    'security.W004',  # SECURE_HSTS_SECONDS warning
    'security.W008',  # SECURE_BROWSER_XSS_FILTER warning
    'security.W003',  # CSRF_COOKIE_SECURE warning
    'security.W016',  # CSRF_COOKIE_HTTPONLY warning
    'security.W017',  # CSRF_FAILURE_VIEW warning
]