"""
Django settings for explore_mada_journey project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from dotenv import load_dotenv
import os
from pathlib import Path
from datetime import timedelta

# Cette section force la désactivation de toute vérification CSRF
import django.conf.global_settings as DEFAULT_SETTINGS



CSRF_TRUSTED_ORIGINS = ["https://api.madagascar-voyagesolidaire.com"]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "[%(asctime)s] %(levelname)s %(name)s: %(message)s"
        },
        "verbose": {
            "format": "[%(asctime)s] %(levelname)s %(name)s "
                      "(%(filename)s:%(lineno)d): %(message)s"
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "formatter": "verbose",
            "filename": os.path.join(BASE_DIR, "logs", "app.log"),
            "maxBytes": 5 * 1024 * 1024,  # 5 MB
            "backupCount": 5,
            "encoding": "utf-8",
        },
        # Optionnel : pour capturer les erreurs critiques séparément
        "errors_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "formatter": "verbose",
            "filename": os.path.join(BASE_DIR, "logs", "errors.log"),
            "level": "ERROR",
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 3,
            "encoding": "utf-8",
        },
    },
    "loggers": {
        # Logger racine
        "": {
            "handlers": ["console", "file"],
            "level": "INFO",
        },
        # Logger pour Django (évite de surcharger avec DEBUG de django.db)
        "django": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        # Exemple : logger pour les erreurs critiques en plus
        "myapp": {
            "handlers": ["console", "file", "errors_file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Import default_headers after defining BASE_DIR
from corsheaders.defaults import default_headers

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=-^c))dt)dbi(g%h2kmtgkp)o!q3cr12=m0cs2#3(j2jg(qodf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# ALLOWED_HOSTS = [
#     'madagascar-voyagesolidaire.com', 
#     'api.madagascar-voyagesolidaire.com', 
#     'administration.madagascar-voyagesolidaire.com'
#     ]

CORS_ALLOWED_ORIGINS = [
    'https://madagascar-voyagesolidaire.com',
    'https://api.madagascar-voyagesolidaire.com',
    'https://administration.madagascar-voyagesolidaire.com',
    'http://5.101.142.84:8000'
]

CSRF_TRUSTED_ORIGINS = [
    'https://madagascar-voyagesolidaire.com',
    'https://api.madagascar-voyagesolidaire.com',
    'https://administration.madagascar-voyagesolidaire.com',
    'http://5.101.142.84:8000'
]

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    "apollo-require-preflight",
    'apollographql-client-name',
    'apollographql-client-version',
    # Add these variations
    'ApolloGraphQL-Client-Name',
    'ApolloGraphQL-Client-Version',
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "graphene_file_upload",
    'graphene_django',
    'graphql_jwt',
    "graphql_jwt.refresh_token",
    'rest_framework',
    'django_filters',
    'mada_journey',
]

GRAPHENE = {
    'SCHEMA': 'schema_root.schema',
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ],
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# En production, définir les en-têtes de sécurité appropriés
# Avec cette configuration, votre application redirigera toutes les requêtes HTTP vers HTTPS et activera les en-têtes HSTS pour appliquer des connexions sécurisées.
# SECURE_HSTS_SECONDS = 3600   # Définir la durée HSTS 
# SECURE_SSL_REDIRECT = True   # Rediriger toutes les requêtes HTTP vers HTTPS

ROOT_URLCONF = os.getenv("ROOT_URLCONF")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = os.getenv("WSGI_APPLICATION")

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'madaga47_solidaire_db',
        'USER': 'madaga47_solidaire_db',    
        'PASSWORD': 'WJVKHdayMuhT5Vyg3Vtr',
        'HOST': '5.101.142.84',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            # Supprimez toutes les options li  es aux plugins
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

AUTH_USER_MODEL = 'mada_journey.Utilisateur'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#Configuration de stockage d'image:
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuration des fichiers statiques
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, 'static'),
]

# Configuration pour le développement - servir les fichiers médias
if DEBUG:
    from django.conf.urls.static import static


# Configuration des tailles d'upload
FILE_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024  # 15MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024   # 15MB

# Configuration de sécurité pour les fichiers
ALLOWED_IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif', '.webp']
MAX_IMAGE_SIZE = 15 * 1024 * 1024  # 15MB

# Configuration du cache pour optimiser l'admin
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

#  Configuration pour le JWT dans GraphQL
GRAPHQL_JWT = {
    'JWT_VERIFY_EXPIRATION': True,
    "JWT_LONG_RUNNING_REFRESH_TOKEN": True,
    'JWT_EXPIRATION_DELTA': timedelta(days=7),
    'JWT_AUTH_HEADER_PREFIX': 'JWT', 
    "JWT_REFRESH_EXPIRATION_DELTA": timedelta(days=7),
    'JWT_ALGORITHM': 'HS256',
}

AUTHENTICATION_BACKENDS = [
    'graphql_jwt.backends.JSONWebTokenBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # Utilisez AllowAny pour un accès public temporaire pendant le développement
        'rest_framework.permissions.AllowAny',
        # En production, utilisez plutôt:
        # 'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Configuration CSRF (désactiver uniquement pour déboguer)
CSRF_COOKIE_SECURE = False  # En production, mettre à True si HTTPS
CSRF_COOKIE_HTTPONLY = False  # Doit être False pour que JS puisse accéder au token
CSRF_USE_SESSIONS = False  # Utiliser des cookies au lieu des sessions
CSRF_COOKIE_SAMESITE = None  # 'None' permet le partage entre sites
SESSION_COOKIE_SAMESITE = None  # 'None' permet le partage entre sites
# SESSION_COOKIE_SECURE = True # En production, mettre à True si HTTPS
# SESSION_COOKIE_HTTPONLY = True # Empêche l'accès JS au cookie de session