export const villages = [
  "Salehy",
  "Ambodiarina",
  "Ambodisovika",
  "Ampangalana",
  "Andranotsara",
  "Sohihy",
  "Ampanambo",
  "Analila",
  "Manonilaza",
  "Masomeloka",
  "Ambalavotaka",
  "Analampotsy",
  "Andonaka",
  "Nosy Varika",
  "Ampohamanitra",
  "Ambodiarana",
  "Analanolona",
  "Ambahy",
  "Ambohitsara",
  "Ampandomana",
];
